//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.26 at 02:43:12 PM CLST 
//


package cl.minsal.api.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FechaDiagnostico" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="DiagnosticoIngresoCentro" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DiagnosticoComite" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DiagnosticoCIE10"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TNM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Estadio"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="5"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DiagnosticoSOME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TipoComite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ECOG" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fechaDiagnostico",
    "diagnosticoIngresoCentro",
    "diagnosticoComite",
    "diagnosticoCIE10",
    "tnm",
    "estadio",
    "diagnosticoSOME",
    "tipoComite",
    "ecog"
})
@XmlRootElement(name = "Diagnostico")
public class Diagnostico {

    @XmlElement(name = "FechaDiagnostico", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaDiagnostico;
    @XmlElement(name = "DiagnosticoIngresoCentro", required = true)
    protected String diagnosticoIngresoCentro;
    @XmlElement(name = "DiagnosticoComite", required = true)
    protected String diagnosticoComite;
    @XmlElement(name = "DiagnosticoCIE10", required = true)
    protected String diagnosticoCIE10;
    @XmlElement(name = "TNM", required = true)
    protected String tnm;
    @XmlElement(name = "Estadio", required = true)
    protected String estadio;
    @XmlElement(name = "DiagnosticoSOME", required = true)
    protected String diagnosticoSOME;
    @XmlElement(name = "TipoComite")
    protected String tipoComite;
    @XmlElement(name = "ECOG")
    protected Integer ecog;

    /**
     * Gets the value of the fechaDiagnostico property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaDiagnostico() {
        return fechaDiagnostico;
    }

    /**
     * Sets the value of the fechaDiagnostico property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaDiagnostico(XMLGregorianCalendar value) {
        this.fechaDiagnostico = value;
    }

    /**
     * Gets the value of the diagnosticoIngresoCentro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosticoIngresoCentro() {
        return diagnosticoIngresoCentro;
    }

    /**
     * Sets the value of the diagnosticoIngresoCentro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosticoIngresoCentro(String value) {
        this.diagnosticoIngresoCentro = value;
    }

    /**
     * Gets the value of the diagnosticoComite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosticoComite() {
        return diagnosticoComite;
    }

    /**
     * Sets the value of the diagnosticoComite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosticoComite(String value) {
        this.diagnosticoComite = value;
    }

    /**
     * Gets the value of the diagnosticoCIE10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosticoCIE10() {
        return diagnosticoCIE10;
    }

    /**
     * Sets the value of the diagnosticoCIE10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosticoCIE10(String value) {
        this.diagnosticoCIE10 = value;
    }

    /**
     * Gets the value of the tnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTNM() {
        return tnm;
    }

    /**
     * Sets the value of the tnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTNM(String value) {
        this.tnm = value;
    }

    /**
     * Gets the value of the estadio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadio() {
        return estadio;
    }

    /**
     * Sets the value of the estadio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadio(String value) {
        this.estadio = value;
    }

    /**
     * Gets the value of the diagnosticoSOME property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosticoSOME() {
        return diagnosticoSOME;
    }

    /**
     * Sets the value of the diagnosticoSOME property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosticoSOME(String value) {
        this.diagnosticoSOME = value;
    }

    /**
     * Gets the value of the tipoComite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoComite() {
        return tipoComite;
    }

    /**
     * Sets the value of the tipoComite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoComite(String value) {
        this.tipoComite = value;
    }

    /**
     * Gets the value of the ecog property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getECOG() {
        return ecog;
    }

    /**
     * Sets the value of the ecog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setECOG(Integer value) {
        this.ecog = value;
    }

}
