//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.26 at 02:43:12 PM CLST 
//


package cl.minsal.api.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NombreEstablecimiento"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="150"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CodigoEstablecimiento"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="99999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ServicioSalud"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="99"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nombreEstablecimiento",
    "codigoEstablecimiento",
    "servicioSalud"
})
@XmlRootElement(name = "Establecimiento")
public class Establecimiento {

    @XmlElement(name = "NombreEstablecimiento", required = true)
    protected String nombreEstablecimiento;
    @XmlElement(name = "CodigoEstablecimiento")
    protected int codigoEstablecimiento;
    @XmlElement(name = "ServicioSalud")
    protected int servicioSalud;

    /**
     * Gets the value of the nombreEstablecimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreEstablecimiento() {
        return nombreEstablecimiento;
    }

    /**
     * Sets the value of the nombreEstablecimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreEstablecimiento(String value) {
        this.nombreEstablecimiento = value;
    }

    /**
     * Gets the value of the codigoEstablecimiento property.
     * 
     */
    public int getCodigoEstablecimiento() {
        return codigoEstablecimiento;
    }

    /**
     * Sets the value of the codigoEstablecimiento property.
     * 
     */
    public void setCodigoEstablecimiento(int value) {
        this.codigoEstablecimiento = value;
    }

    /**
     * Gets the value of the servicioSalud property.
     * 
     */
    public int getServicioSalud() {
        return servicioSalud;
    }

    /**
     * Sets the value of the servicioSalud property.
     * 
     */
    public void setServicioSalud(int value) {
        this.servicioSalud = value;
    }

}
