//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.26 at 02:43:12 PM CLST 
//


package cl.minsal.api.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://uv.com/types/rnc}Paciente"/&gt;
 *         &lt;element ref="{http://uv.com/types/rnc}CreadorDocumento"/&gt;
 *         &lt;element name="PaisEmisor"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TipoDocumento" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paciente",
    "creadorDocumento",
    "paisEmisor",
    "tipoDocumento"
})
@XmlRootElement(name = "HeaderDoc")
public class HeaderDoc {

    @XmlElement(name = "Paciente", required = true)
    protected Paciente paciente;
    @XmlElement(name = "CreadorDocumento", required = true)
    protected CreadorDocumento creadorDocumento;
    @XmlElement(name = "PaisEmisor")
    protected int paisEmisor;
    @XmlElement(name = "TipoDocumento")
    protected int tipoDocumento;

    /**
     * Gets the value of the paciente property.
     * 
     * @return
     *     possible object is
     *     {@link Paciente }
     *     
     */
    public Paciente getPaciente() {
        return paciente;
    }

    /**
     * Sets the value of the paciente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paciente }
     *     
     */
    public void setPaciente(Paciente value) {
        this.paciente = value;
    }

    /**
     * Gets the value of the creadorDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link CreadorDocumento }
     *     
     */
    public CreadorDocumento getCreadorDocumento() {
        return creadorDocumento;
    }

    /**
     * Sets the value of the creadorDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreadorDocumento }
     *     
     */
    public void setCreadorDocumento(CreadorDocumento value) {
        this.creadorDocumento = value;
    }

    /**
     * Gets the value of the paisEmisor property.
     * 
     */
    public int getPaisEmisor() {
        return paisEmisor;
    }

    /**
     * Sets the value of the paisEmisor property.
     * 
     */
    public void setPaisEmisor(int value) {
        this.paisEmisor = value;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     */
    public int getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     */
    public void setTipoDocumento(int value) {
        this.tipoDocumento = value;
    }

}
