//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.26 at 02:43:12 PM CLST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uv.com/types/rnc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@javax.annotation.Generated({
    "XJC",
    "JAXB2 Annotate Plugin"
})
package cl.minsal.api.types;
