//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.26 at 02:43:12 PM CLST 
//


package cl.minsal.api.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MedicoTratante"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="120"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TratamientoGeneral"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DescripcionTratamiento"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="150"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="EstadoTratamiento"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                         &lt;minInclusive value="1"/&gt;
 *                         &lt;maxInclusive value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ResolucionComite" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DescripcionResolucionComite" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="150"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Comite"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="MedicoParticipante" maxOccurs="unbounded"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;length value="120"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Tratamientos"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://uv.com/types/rnc}Tratamiento" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "medicoTratante",
    "tratamientoGeneral",
    "tratamientos"
})
@XmlRootElement(name = "ResolucionTratamientoDoc")
public class ResolucionTratamientoDoc {

    @XmlElement(name = "MedicoTratante", required = true)
    protected String medicoTratante;
    @XmlElement(name = "TratamientoGeneral", required = true)
    protected ResolucionTratamientoDoc.TratamientoGeneral tratamientoGeneral;
    @XmlElement(name = "Tratamientos", required = true)
    protected ResolucionTratamientoDoc.Tratamientos tratamientos;

    /**
     * Gets the value of the medicoTratante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicoTratante() {
        return medicoTratante;
    }

    /**
     * Sets the value of the medicoTratante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicoTratante(String value) {
        this.medicoTratante = value;
    }

    /**
     * Gets the value of the tratamientoGeneral property.
     * 
     * @return
     *     possible object is
     *     {@link ResolucionTratamientoDoc.TratamientoGeneral }
     *     
     */
    public ResolucionTratamientoDoc.TratamientoGeneral getTratamientoGeneral() {
        return tratamientoGeneral;
    }

    /**
     * Sets the value of the tratamientoGeneral property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResolucionTratamientoDoc.TratamientoGeneral }
     *     
     */
    public void setTratamientoGeneral(ResolucionTratamientoDoc.TratamientoGeneral value) {
        this.tratamientoGeneral = value;
    }

    /**
     * Gets the value of the tratamientos property.
     * 
     * @return
     *     possible object is
     *     {@link ResolucionTratamientoDoc.Tratamientos }
     *     
     */
    public ResolucionTratamientoDoc.Tratamientos getTratamientos() {
        return tratamientos;
    }

    /**
     * Sets the value of the tratamientos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResolucionTratamientoDoc.Tratamientos }
     *     
     */
    public void setTratamientos(ResolucionTratamientoDoc.Tratamientos value) {
        this.tratamientos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DescripcionTratamiento"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="150"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="EstadoTratamiento"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *               &lt;minInclusive value="1"/&gt;
     *               &lt;maxInclusive value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ResolucionComite" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DescripcionResolucionComite" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="150"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Comite"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="MedicoParticipante" maxOccurs="unbounded"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;length value="120"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "descripcionTratamiento",
        "estadoTratamiento",
        "resolucionComite",
        "descripcionResolucionComite",
        "comite"
    })
    public static class TratamientoGeneral {

        @XmlElement(name = "DescripcionTratamiento", required = true)
        protected String descripcionTratamiento;
        @XmlElement(name = "EstadoTratamiento")
        protected int estadoTratamiento;
        @XmlElement(name = "ResolucionComite", required = true)
        protected String resolucionComite;
        @XmlElement(name = "DescripcionResolucionComite")
        protected String descripcionResolucionComite;
        @XmlElement(name = "Comite", required = true)
        protected ResolucionTratamientoDoc.TratamientoGeneral.Comite comite;

        /**
         * Gets the value of the descripcionTratamiento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescripcionTratamiento() {
            return descripcionTratamiento;
        }

        /**
         * Sets the value of the descripcionTratamiento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescripcionTratamiento(String value) {
            this.descripcionTratamiento = value;
        }

        /**
         * Gets the value of the estadoTratamiento property.
         * 
         */
        public int getEstadoTratamiento() {
            return estadoTratamiento;
        }

        /**
         * Sets the value of the estadoTratamiento property.
         * 
         */
        public void setEstadoTratamiento(int value) {
            this.estadoTratamiento = value;
        }

        /**
         * Gets the value of the resolucionComite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResolucionComite() {
            return resolucionComite;
        }

        /**
         * Sets the value of the resolucionComite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResolucionComite(String value) {
            this.resolucionComite = value;
        }

        /**
         * Gets the value of the descripcionResolucionComite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescripcionResolucionComite() {
            return descripcionResolucionComite;
        }

        /**
         * Sets the value of the descripcionResolucionComite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescripcionResolucionComite(String value) {
            this.descripcionResolucionComite = value;
        }

        /**
         * Gets the value of the comite property.
         * 
         * @return
         *     possible object is
         *     {@link ResolucionTratamientoDoc.TratamientoGeneral.Comite }
         *     
         */
        public ResolucionTratamientoDoc.TratamientoGeneral.Comite getComite() {
            return comite;
        }

        /**
         * Sets the value of the comite property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResolucionTratamientoDoc.TratamientoGeneral.Comite }
         *     
         */
        public void setComite(ResolucionTratamientoDoc.TratamientoGeneral.Comite value) {
            this.comite = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="MedicoParticipante" maxOccurs="unbounded"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;length value="120"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "medicoParticipante"
        })
        public static class Comite {

            @XmlElement(name = "MedicoParticipante", required = true)
            protected List<String> medicoParticipante;

            /**
             * Gets the value of the medicoParticipante property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the medicoParticipante property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMedicoParticipante().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getMedicoParticipante() {
                if (medicoParticipante == null) {
                    medicoParticipante = new ArrayList<String>();
                }
                return this.medicoParticipante;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://uv.com/types/rnc}Tratamiento" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tratamiento"
    })
    public static class Tratamientos {

        @XmlElement(name = "Tratamiento", required = true)
        protected List<Tratamiento> tratamiento;

        /**
         * Gets the value of the tratamiento property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tratamiento property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTratamiento().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tratamiento }
         * 
         * 
         */
        public List<Tratamiento> getTratamiento() {
            if (tratamiento == null) {
                tratamiento = new ArrayList<Tratamiento>();
            }
            return this.tratamiento;
        }

    }

}
