//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.26 at 02:43:12 PM CLST 
//


package cl.minsal.api.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MedicoDerivador"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CentroDerivador"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://uv.com/types/rnc}Establecimiento"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FechaPrimeraConsulta" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="BreveHistoria"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="150"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MotivoDerivacion"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "medicoDerivador",
    "centroDerivador",
    "fechaPrimeraConsulta",
    "breveHistoria",
    "motivoDerivacion"
})
@XmlRootElement(name = "Sospecha")
public class Sospecha {

    @XmlElement(name = "MedicoDerivador", required = true)
    protected String medicoDerivador;
    @XmlElement(name = "CentroDerivador", required = true)
    protected Sospecha.CentroDerivador centroDerivador;
    @XmlElement(name = "FechaPrimeraConsulta", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaPrimeraConsulta;
    @XmlElement(name = "BreveHistoria", required = true)
    protected String breveHistoria;
    @XmlElement(name = "MotivoDerivacion")
    protected int motivoDerivacion;

    /**
     * Gets the value of the medicoDerivador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicoDerivador() {
        return medicoDerivador;
    }

    /**
     * Sets the value of the medicoDerivador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicoDerivador(String value) {
        this.medicoDerivador = value;
    }

    /**
     * Gets the value of the centroDerivador property.
     * 
     * @return
     *     possible object is
     *     {@link Sospecha.CentroDerivador }
     *     
     */
    public Sospecha.CentroDerivador getCentroDerivador() {
        return centroDerivador;
    }

    /**
     * Sets the value of the centroDerivador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sospecha.CentroDerivador }
     *     
     */
    public void setCentroDerivador(Sospecha.CentroDerivador value) {
        this.centroDerivador = value;
    }

    /**
     * Gets the value of the fechaPrimeraConsulta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaPrimeraConsulta() {
        return fechaPrimeraConsulta;
    }

    /**
     * Sets the value of the fechaPrimeraConsulta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaPrimeraConsulta(XMLGregorianCalendar value) {
        this.fechaPrimeraConsulta = value;
    }

    /**
     * Gets the value of the breveHistoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreveHistoria() {
        return breveHistoria;
    }

    /**
     * Sets the value of the breveHistoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreveHistoria(String value) {
        this.breveHistoria = value;
    }

    /**
     * Gets the value of the motivoDerivacion property.
     * 
     */
    public int getMotivoDerivacion() {
        return motivoDerivacion;
    }

    /**
     * Sets the value of the motivoDerivacion property.
     * 
     */
    public void setMotivoDerivacion(int value) {
        this.motivoDerivacion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://uv.com/types/rnc}Establecimiento"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "establecimiento"
    })
    public static class CentroDerivador {

        @XmlElement(name = "Establecimiento", required = true)
        protected Establecimiento establecimiento;

        /**
         * Gets the value of the establecimiento property.
         * 
         * @return
         *     possible object is
         *     {@link Establecimiento }
         *     
         */
        public Establecimiento getEstablecimiento() {
            return establecimiento;
        }

        /**
         * Sets the value of the establecimiento property.
         * 
         * @param value
         *     allowed object is
         *     {@link Establecimiento }
         *     
         */
        public void setEstablecimiento(Establecimiento value) {
            this.establecimiento = value;
        }

    }

}
