//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.26 at 02:43:12 PM CLST 
//


package cl.minsal.api.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TipoTratamiento"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IntencionTratamiento"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FechaIntencion" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="FechaComite" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Medicamentos" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Medicamento" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipoTratamiento",
    "intencionTratamiento",
    "fechaIntencion",
    "fechaComite",
    "medicamentos"
})
@XmlRootElement(name = "Tratamiento")
public class Tratamiento {

    @XmlElement(name = "TipoTratamiento")
    protected int tipoTratamiento;
    @XmlElement(name = "IntencionTratamiento")
    protected int intencionTratamiento;
    @XmlElement(name = "FechaIntencion", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaIntencion;
    @XmlElement(name = "FechaComite", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaComite;
    @XmlElement(name = "Medicamentos")
    protected Tratamiento.Medicamentos medicamentos;

    /**
     * Gets the value of the tipoTratamiento property.
     * 
     */
    public int getTipoTratamiento() {
        return tipoTratamiento;
    }

    /**
     * Sets the value of the tipoTratamiento property.
     * 
     */
    public void setTipoTratamiento(int value) {
        this.tipoTratamiento = value;
    }

    /**
     * Gets the value of the intencionTratamiento property.
     * 
     */
    public int getIntencionTratamiento() {
        return intencionTratamiento;
    }

    /**
     * Sets the value of the intencionTratamiento property.
     * 
     */
    public void setIntencionTratamiento(int value) {
        this.intencionTratamiento = value;
    }

    /**
     * Gets the value of the fechaIntencion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaIntencion() {
        return fechaIntencion;
    }

    /**
     * Sets the value of the fechaIntencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaIntencion(XMLGregorianCalendar value) {
        this.fechaIntencion = value;
    }

    /**
     * Gets the value of the fechaComite property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaComite() {
        return fechaComite;
    }

    /**
     * Sets the value of the fechaComite property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaComite(XMLGregorianCalendar value) {
        this.fechaComite = value;
    }

    /**
     * Gets the value of the medicamentos property.
     * 
     * @return
     *     possible object is
     *     {@link Tratamiento.Medicamentos }
     *     
     */
    public Tratamiento.Medicamentos getMedicamentos() {
        return medicamentos;
    }

    /**
     * Sets the value of the medicamentos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tratamiento.Medicamentos }
     *     
     */
    public void setMedicamentos(Tratamiento.Medicamentos value) {
        this.medicamentos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Medicamento" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "medicamento"
    })
    public static class Medicamentos {

        @XmlElement(name = "Medicamento", required = true)
        protected List<Object> medicamento;

        /**
         * Gets the value of the medicamento property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the medicamento property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMedicamento().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getMedicamento() {
            if (medicamento == null) {
                medicamento = new ArrayList<Object>();
            }
            return this.medicamento;
        }

    }

}
